---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: 'hub.example.com/ansible-automation-platform-24/ee-minimal-rhel9:latest'
  EE_BUILDER_IMAGE: 'hub.example.com/ansible-builder-rhel8'
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt