#/bin/bash

echo "HANA CONFIG CHECK - Report"
echo "##########################################################"
echo "3108302 - SAP HANA DB: Recommended OS Settings for RHEL 9"
echo "##########################################################"
echo "_____________________"
echo "REDHAT VERSION"
echo "Expected Result: 9.2"
cat /etc/redhat-release
echo "_____________________"
echo "REDHAT KERNEL VERSION"
echo "Expected Result: 5.14.0-284.25.1.el9_2 or newer"
uname -r
echo "_____________________"
echo "SELINUX STATUS"
echo "Expected Result: Disabled"
getenforce
echo "_____________________"
echo "TUNED PROFILE STATUS"
echo "Expected Result: sap-hana profile"
tuned-adm active
echo "_____________________"
echo "DISABLE ABRT,CORE DUMPS,KDUMP(Check if is disabled)"
echo "Expected Result: The services are disabled"
echo "Result: $(systemctl status abrtd )"
echo "Result: $(systemctl status abrt-ccpp )"
echo "Result: $(systemctl status kdump )"
echo "_____________________"
echo "TURN OFF AUTO-NUMA BALANCING"
echo "Expected Result: kernel.numa_balancing=0"
sysctl kernel.numa_balancing
echo "SERVICE NUMAD"
echo "Expected Result: Disabled"
echo "Result: $(systemctl status numad )"
echo "_____________________"
echo "DISABLE TRANSPARENT HUGEPAGES(THP)"
echo "Expected Result: always madvise [never]"
cat /sys/kernel/mm/transparent_hugepage/enabled
echo "_____________________"
echo "Cluster-ON-DIE(COD) sub-NUMA clustering techonology"
echo "N/A"
echo "_____________________"
echo "CONFIGURE C-STATES FOR LOWER LATENCY IN LINUX(INTEL PLATFORM ONLY)"
echo "Expected Result: Append processor.max_cstate=1 | intel_idle.max_cstate=1"
cat /etc/default/grub
echo "_____________________"
echo "CONFIGURE CPU GOVERNOR FOR PERFORMANCE(INTEL64PLATFORM ONLY)"
echo "Expected Result: cpupower frequency-set -g performance in /etc/rc.d/rc.local"
cat /etc/rc.d/rc.local 
echo "_____________________"
echo "CONFIGURE ENERGY PERFOMANCE BIAS(EPB , INTEL 64 platform only"
echo "Expected Result: cpupower set -b 0 in /etc/init.d/boot.local"
cat /etc/init.d/boot.local
echo "_____________________"
echo "ENABLE TSX RHEL8.4 AND LATER,INTEL PLATFORM ONLY"
echo "Expected Result: tsx=on"
sudo grubby --info=ALL | grep -i tsx
echo ""
echo "_____________________"
echo "Disable Kernel Samepage merging KSM"
echo "Expected Result: 0"
cat /sys/kernel/mm/ksm/run
echo "_____________________"
echo "Increase Kernel.pid_max Only RHEL8.0 and 8.1"
echo "NA"
echo "_____________________"
echo "IBM ENERGY SCALE FOR POWER9 PROCESSOR-BASED SYSTEMS"
echo "NA"

echo "########################################################################"
echo "NOTA:3216146 - Linux: Running SAP applications compiled with GCC 11.x "
echo "#######################################################################"
echo "_______________________"
echo "GCC 11.X Package"
echo "Expected Result:compat-sap-c++-11-11.1.1-6.el8_2.x86_64 or newer "
echo "Result: $(rpm -q compat-sap-c++-12 )"
echo "______________________"
echo "Libatomic Package"
echo "Expected Result:libatomic-8.3.1-5.el8.x86_64 or newer "
echo "Result: $(rpm -q libatomic)"
echo "################################"
echo "3108316 - Red Hat Enterprise Linux 9.x: Installation and Configuration"
echo "################################"
echo "______________________"
echo "uuid|libnsl|tcsh|nfs-utils Package"
echo "Output:"
echo "Result: $(rpm -q uuid libnsl tcsh nfs-utils )"
echo "______________________"
echo "expect | gtk2 | krb5-workstation | libatomic|libcanberra-gtk2| libtool-ltdl| numactl | PackageKit-gtk3-module| xorg-x11-xauth| chkconfig | compat-openssl11 | tuned | tuned-profiles-sap-hana | graphviz | iptraf-ng | lm_sensors Package"
echo "Output:"
echo "Result: $(rpm -q expect gtk2 krb5-workstation libatomic libcanberra-gtk2  libtool-ltdl  numactl  PackageKit-gtk3-module  xorg-x11-xauth  chkconfig   compat-openssl11  tuned  tuned-profiles-sap-hana   graphviz  iptraf-ng  lm_sensors )"
echo "______________________"
echo "Hostname: $(hostnamectl hostname)"
echo "SELINUX: $(getenforce)"
echo "/etc/hosts $(cat /etc/hosts)"
echo "NTP Config: $(systemctl status chronyd.service)"
echo "Firewall:(if enabled, turn off) $(systemctl status firewalld)"
echo "UUID Status $(systemctl status uuid)"
echo "TMPFS Conf: SAP Note:941735-chapter B)"
echo "Linux Kernel Parameters -  Verify Manually"
cat /etc/sysctl.d/sap.conf
echo "Process Resource Limits --> necessário verificar config da nota"
echo "systemd-tmpfiles --> necessário verificar config da nota"
