services:
  postgres_db:
    image: postgres:latest
    container_name: postgresdb
    restart: always
    environment:
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    networks:
      - traefik-network
    volumes:
      - postgres_db:/var/lib/postgresql/data
    depends_on:
      - traefik

  traefik:
    image: "traefik:v3.1"
    container_name: "traefik"
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - traefik-network
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  postgres_db:
    driver: local

networks:
  traefik-network:
    driver: bridge